version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/desafio_atalhos
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:7.0
    container_name: mongodb_desafio
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_desafio
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
